BEGIN;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tweets CASCADE;

CREATE TABLE users (
 user_id SERIAL PRIMARY KEY,
 username VARCHAR NOT NULL
);

CREATE TABLE tweets (
 tweet_id SERIAL PRIMARY KEY,
 content TEXT NOT NULL,
 likes INT NOT NULL DEFAULT 0,
 user_id INT NOT NULL
);

COMMIT;
